### PR TITLE
Specify syn element to update

### PR DESCRIPTION
**Pull request by sanjayankur31**
- specify which synaptic element is to be updated
- added a simple test case
- merged with master to updated the code base

### CODE REVIEW

**Comment by sdiazpier** [comment]
Wonderful! thanks so much dear @sanjayankur31. I have just one comment, the change in the nest_names.h file seems unnecessary. Is this intentional?
Otherwise is good to go from my side.

**Comment by sanjayankur31** [comment]
Do you mean this one?

https://github.com/sdiazpier/nest-simulator/pull/2/commits/02f23734fc50290351c5398ca7f05db2ba20b784#diff-095c2c7098b71b323018d64beac17623L403

I'm not even sure where that came from - was probably dealing with a conflict and got carried away. I can fix that but it'll need a force push since the commit will change - is that OK? :(

**Comment by sdiazpier** [comment]
Yes that one... I can merge first and then we do the change. Maybe this would be better ;)

**Comment by sanjayankur31** [comment]
Yeh, probably easier :)

**Pull request merged**
