### PR TITLE
Fixes the test

### PR DESCRIPTION
**Pull request by BSVogler**
Removes the test for the removed function and only checks for nest.GetKernelStatus.

### CODE REVIEW

**Review by sdiazpier — APPROVED** [review]
Dear @BSVogler thanks for removing the get sp status test. I think this addresses the immediate needs for the PR.

**Comment by stinebuu** [comment]
Dear @sdiazpier! Could you please press the green merge button? Neither @BSVogler or me have write access on your branch ;)

**Comment by sdiazpier** [comment]
Sorry I thought I had solved this yesterday.

**Comment by stinebuu** [comment]
Thanks!

**Pull request merged**
